// Code generated by cmd/gen-types; DO NOT EDIT.
package {{ .pkg }}

import (
	"database/sql/driver"
	"errors"

	"github.com/google/uuid"
)
{{range .types}}
type {{ . }} uuid.UUID

var {{ . }}Nil {{ . }}

func New{{ . }}() {{ . }} {
	return {{ . }}(uuid.New())
}

func (id {{ . }}) String() string {
	return (uuid.UUID)(id).String()
}

func (id *{{ . }}) Scan(src interface{}) error {
	return (*uuid.UUID)(id).Scan(src)
}

func (id {{ . }}) Value() (driver.Value, error) {
	return (uuid.UUID)(id).Value()
}

func (id {{ . }}) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *{{ . }}) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id {{ . }}) IsZero() bool {
	return id.String() == uuid.Nil.String()
}

func (id {{ . }}) Matches(x interface{}) bool {
	switch x := x.(type) {
	case {{ . }}:
		return id.String() == x.String()
	}
	return false
}

func (id {{ . }}) Validate() error {
	if id.IsZero() {
		return errors.New("zero {{ . }}")
	}
	return nil
}

func (id {{ . }}) AsPointer() *{{ . }} {
	if id.IsZero() {
		return nil
	}
	return &id
}
{{end}}
type TypeSet = interface {
	{{ .argType }}
}

func Parse[T TypeSet](s string) (T, error) {
	id, err := uuid.Parse(s)

	return T(id), err
}

func MustParse[T TypeSet](s string) T {
	return T(uuid.MustParse(s))
}
