// Code generated by cmd/gen-types; DO NOT EDIT.
package types

import (
	"database/sql/driver"
	"errors"

	"github.com/google/uuid"
)

type ChatID uuid.UUID

var ChatIDNil ChatID

func NewChatID() ChatID {
	return ChatID(uuid.New())
}

func (id ChatID) String() string {
	return (uuid.UUID)(id).String()
}

func (id *ChatID) Scan(src interface{}) error {
	return (*uuid.UUID)(id).Scan(src)
}

func (id ChatID) Value() (driver.Value, error) {
	return (uuid.UUID)(id).Value()
}

func (id ChatID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *ChatID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id ChatID) IsZero() bool {
	return id.String() == uuid.Nil.String()
}

func (id ChatID) Matches(x interface{}) bool {
	switch x := x.(type) {
	case ChatID:
		return id.String() == x.String()
	}
	return false
}

func (id ChatID) Validate() error {
	if id.IsZero() {
		return errors.New("zero ChatID")
	}
	return nil
}

type MessageID uuid.UUID

var MessageIDNil MessageID

func NewMessageID() MessageID {
	return MessageID(uuid.New())
}

func (id MessageID) String() string {
	return (uuid.UUID)(id).String()
}

func (id *MessageID) Scan(src interface{}) error {
	return (*uuid.UUID)(id).Scan(src)
}

func (id MessageID) Value() (driver.Value, error) {
	return (uuid.UUID)(id).Value()
}

func (id MessageID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *MessageID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id MessageID) IsZero() bool {
	return id.String() == uuid.Nil.String()
}

func (id MessageID) Matches(x interface{}) bool {
	switch x := x.(type) {
	case MessageID:
		return id.String() == x.String()
	}
	return false
}

func (id MessageID) Validate() error {
	if id.IsZero() {
		return errors.New("zero MessageID")
	}
	return nil
}

type ProblemID uuid.UUID

var ProblemIDNil ProblemID

func NewProblemID() ProblemID {
	return ProblemID(uuid.New())
}

func (id ProblemID) String() string {
	return (uuid.UUID)(id).String()
}

func (id *ProblemID) Scan(src interface{}) error {
	return (*uuid.UUID)(id).Scan(src)
}

func (id ProblemID) Value() (driver.Value, error) {
	return (uuid.UUID)(id).Value()
}

func (id ProblemID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *ProblemID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id ProblemID) IsZero() bool {
	return id.String() == uuid.Nil.String()
}

func (id ProblemID) Matches(x interface{}) bool {
	switch x := x.(type) {
	case ProblemID:
		return id.String() == x.String()
	}
	return false
}

func (id ProblemID) Validate() error {
	if id.IsZero() {
		return errors.New("zero ProblemID")
	}
	return nil
}

type RequestID uuid.UUID

var RequestIDNil RequestID

func NewRequestID() RequestID {
	return RequestID(uuid.New())
}

func (id RequestID) String() string {
	return (uuid.UUID)(id).String()
}

func (id *RequestID) Scan(src interface{}) error {
	return (*uuid.UUID)(id).Scan(src)
}

func (id RequestID) Value() (driver.Value, error) {
	return (uuid.UUID)(id).Value()
}

func (id RequestID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *RequestID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id RequestID) IsZero() bool {
	return id.String() == uuid.Nil.String()
}

func (id RequestID) Matches(x interface{}) bool {
	switch x := x.(type) {
	case RequestID:
		return id.String() == x.String()
	}
	return false
}

func (id RequestID) Validate() error {
	if id.IsZero() {
		return errors.New("zero RequestID")
	}
	return nil
}

type UserID uuid.UUID

var UserIDNil UserID

func NewUserID() UserID {
	return UserID(uuid.New())
}

func (id UserID) String() string {
	return (uuid.UUID)(id).String()
}

func (id *UserID) Scan(src interface{}) error {
	return (*uuid.UUID)(id).Scan(src)
}

func (id UserID) Value() (driver.Value, error) {
	return (uuid.UUID)(id).Value()
}

func (id UserID) MarshalText() ([]byte, error) {
	return (uuid.UUID)(id).MarshalText()
}

func (id *UserID) UnmarshalText(data []byte) error {
	return (*uuid.UUID)(id).UnmarshalText(data)
}

func (id UserID) IsZero() bool {
	return id.String() == uuid.Nil.String()
}

func (id UserID) Matches(x interface{}) bool {
	switch x := x.(type) {
	case UserID:
		return id.String() == x.String()
	}
	return false
}

func (id UserID) Validate() error {
	if id.IsZero() {
		return errors.New("zero UserID")
	}
	return nil
}

func Parse[T ChatID | MessageID | ProblemID | RequestID | UserID](s string) (T, error) {
	id, err := uuid.Parse(s)

	return T(id), err
}

func MustParse[T ChatID | MessageID | ProblemID | RequestID | UserID](s string) T {
	return T(uuid.MustParse(s))
}
