version: "3.8"

services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    environment:
      URLS: "[
        {url: 'doc/client.v1.swagger.yml', name: 'Bank Support Chat Client API'},
        {url: 'doc/client.events.swagger.yml', name: 'Bank Support Client Events'},
        {url: 'doc/manager.v1.swagger.yml', name: 'Bank Support Chat Manager API'},
      ]"
    profiles: [ swagger-ui ]
    volumes:
      - ./../../api:/usr/share/nginx/html/doc
    ports:
      - "127.0.0.1:3011:8080"
