// Code generated by options-gen. DO NOT EDIT.
package freehandssignal

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	mLoadSvc managerLoadService,
	mPool managerPool,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.mLoadSvc = mLoadSvc

	o.mPool = mPool

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("mLoadSvc", _validate_Options_mLoadSvc(o)))
	errs.Add(errors461e464ebed9.NewValidationError("mPool", _validate_Options_mPool(o)))
	return errs.AsError()
}

func _validate_Options_mLoadSvc(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.mLoadSvc, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `mLoadSvc` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_mPool(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.mPool, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `mPool` did not pass the test: %w", err)
	}
	return nil
}
