// Code generated by options-gen. DO NOT EDIT.
package managerload

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	maxProblemsAtTime int,
	problemsRepo problemsRepository,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.maxProblemsAtTime = maxProblemsAtTime

	o.problemsRepo = problemsRepo

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("maxProblemsAtTime", _validate_Options_maxProblemsAtTime(o)))
	errs.Add(errors461e464ebed9.NewValidationError("problemsRepo", _validate_Options_problemsRepo(o)))
	return errs.AsError()
}

func _validate_Options_maxProblemsAtTime(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.maxProblemsAtTime, "required,min=1,max=30"); err != nil {
		return fmt461e464ebed9.Errorf("field `maxProblemsAtTime` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_problemsRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.problemsRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `problemsRepo` did not pass the test: %w", err)
	}
	return nil
}
