[global]
env = "dev"

[log]
level = "info"

[sentry]
dsn = "http://4c3d121c461747148f16f7820a9c0959@127.0.0.1:9000/3"

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
[servers.client.required_access]
resource = "chat-ui-client"
role = "support-chat-client"

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "Bank"
client_id = "chat-service"
client_secret = "BX6KbVXoZREf3hQI7mnRBwTW6wJ0SS8e"
debug_mode = false

[db]
addr = "127.0.0.1:5432"
user = "chat-service"
password = "chat-service"
database = "chat-service"
debug_mode = false
