[global]
env = "dev"

[log]
level = "info"

[sentry]
dsn = "http://2ada15bfebc5467f9cd07ccc8fecdfa2@127.0.0.1:9000/2"

[servers]
[servers.debug]
addr = ":8079"

[servers.client]
addr = ":8080"
allow_origins = ["http://localhost:3011", "http://localhost:3000"]
sec_ws_protocol = "chat-service-protocol"
[servers.client.required_access]
resource = "chat-ui-client"
role = "support-chat-client"

[servers.manager]
addr = ":8081"
allow_origins = ["http://localhost:3011", "http://localhost:3001"]
sec_ws_protocol = "chat-service-protocol"
[servers.manager.required_access]
resource = "chat-ui-manager"
role = "support-chat-manager"

[stores]
[stores.psql]
addr = "127.0.0.1:5432"
username = "chat-service"
password = "chat-service"
database = "chat-service"
debug = false

[clients]
[clients.keycloak]
base_path = "http://localhost:3010"
realm = "Bank"
client_id = "chat-service"
client_secret = "BX6KbVXoZREf3hQI7mnRBwTW6wJ0SS8e"
debug_mode = false

[services]
[services.manager_load]
max_problems_at_same_time = 5

[services.msg_producer]
brokers = ["localhost:9092"]
topic = "chat.messages"
batch_size = 1
encrypt_key = "87029346716384975967870919549578" # Leave it blank to disable encryption.

[services.outbox]
workers = 2
idle_time = "1s"
reserve_for = "5m"
