// Code generated by options-gen. DO NOT EDIT.
package managerassignedtoproblemjob

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	eventStream eventStream,
	chatRepo chatRepository,
	problemRepo problemRepository,
	msgRepo messageRepository,
	managerLoad managerLoadService,
	options ...OptOptionsSetter,
) Options {
	o := Options{}

	// Setting defaults from field tag (if present)

	o.eventStream = eventStream

	o.chatRepo = chatRepo

	o.problemRepo = problemRepo

	o.msgRepo = msgRepo

	o.managerLoad = managerLoad

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("eventStream", _validate_Options_eventStream(o)))
	errs.Add(errors461e464ebed9.NewValidationError("chatRepo", _validate_Options_chatRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("problemRepo", _validate_Options_problemRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("msgRepo", _validate_Options_msgRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("managerLoad", _validate_Options_managerLoad(o)))
	return errs.AsError()
}

func _validate_Options_eventStream(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventStream, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventStream` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_chatRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.chatRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `chatRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_problemRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.problemRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `problemRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_msgRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.msgRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `msgRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_managerLoad(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.managerLoad, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `managerLoad` did not pass the test: %w", err)
	}
	return nil
}
