openapi: 3.0.0
info:
  title: Bank Support Chat Client Events
  version: v1

servers:
  - url: ws://localhost:8080/ws
    description: Development server

paths:
  /stub:
    get:
      description: It uses for generating events. Otherwise it doesn't.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'

components:
  schemas:
    MessageId:
      required: [ messageId ]
      properties:
        messageId:
          type: string
          format: uuid
          x-go-type: types.MessageID
          x-go-type-import:
            path: "github.com/zestagio/chat-service/internal/types"

    Message:
      allOf:
        - $ref: "#/components/schemas/MessageId"
        - type: object
          required: [ body, createdAt, isService ]
          properties:
            authorId:
              type: string
              format: uuid
              x-go-type: types.UserID
              x-go-type-import:
                path: "github.com/zestagio/chat-service/internal/types"
            body:
              type: string
            createdAt:
              type: string
              format: date-time
            isService:
              type: boolean

    Event:
      required: [ eventType, eventId, requestId ]
      properties:
        eventType:
          type: string
        eventId:
          type: string
          format: uuid
          x-go-type: types.EventID
          x-go-type-import:
            path: "github.com/zestagio/chat-service/internal/types"
        requestId:
          type: string
          format: uuid
          x-go-type: types.RequestID
          x-go-type-import:
            path: "github.com/zestagio/chat-service/internal/types"
      oneOf:
        - $ref: "#/components/schemas/NewMessageEvent"
        - $ref: "#/components/schemas/MessageSentEvent"
        - $ref: "#/components/schemas/MessageBlockedEvent"
      discriminator:
        propertyName: eventType

    NewMessageEvent:
      $ref: "#/components/schemas/Message"

    MessageSentEvent:
      $ref: "#/components/schemas/MessageId"

    MessageBlockedEvent:
      $ref: "#/components/schemas/MessageId"
