openapi: 3.0.0
info:
  title: Bank Support Chat Manager Events
  version: v1

servers:
  - url: ws://localhost:8081/ws
    description: Development server

paths:
  /stub:
    get:
      description: It uses for generating events. Otherwise it doesn't.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'

components:
  schemas:
    ChatId:
      required: [ chatId ]
      properties:
        chatId:
          type: string
          format: uuid
          x-go-type: types.ChatID
          x-go-type-import:
            path: "github.com/zestagio/chat-service/internal/types"

    Message:
      allOf:
        - $ref: "#/components/schemas/ChatId"
        - type: object
          required: [ clientId, canTakeMoreProblems ]
          properties:
            clientId:
              type: string
              format: uuid
              x-go-type: types.UserID
              x-go-type-import:
                path: "github.com/zestagio/chat-service/internal/types"
            canTakeMoreProblems:
              type: boolean

    Event:
      required: [ eventType, eventId, requestId ]
      properties:
        eventType:
          type: string
        eventId:
          type: string
          format: uuid
          x-go-type: types.EventID
          x-go-type-import:
            path: "github.com/zestagio/chat-service/internal/types"
        requestId:
          type: string
          format: uuid
          x-go-type: types.RequestID
          x-go-type-import:
            path: "github.com/zestagio/chat-service/internal/types"
      oneOf:
        - $ref: "#/components/schemas/NewChatEvent"
      discriminator:
        propertyName: eventType
        mapping:
          NewChatEvent: "#/components/schemas/NewChatEvent"

    NewChatEvent:
      $ref: "#/components/schemas/Message"
